kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csi-pvc
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc