kind: VolumeSnapshot
apiVersion: snapshot.storage.k8s.io/v1alpha1
metadata:
  name: csi-hostpath-snapshot
  namespace: kube-system
spec:
  snapshotClassName: csi-hostpath-snapshot
  source:
    name: csi-pvc
    kind: PersistentVolumeClaim
#---
#kind: VolumeSnapshot
#apiVersion: snapshot.storage.k8s.io/v1beta1
#metadata:
#  name: csi-hostpath-snapshot
#  namespace: kube-system
#spec:
#  volumeSnapshotClassName: csi-hostpath-snapshot
#  source:
#    persistentVolumeClaimName: csi-pvc
